version: "3.6"

services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:latest
    volumes:
      - db_new:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}

  web:
    container_name: web
    build:
      dockerfile: _prod/Dockerfile
      context: .
    command: uvicorn main:Blogo --host 0.0.0.0 --port 80 --workers 4 --reload
    volumes:
      - .:/code
    ports:
      - '8000:80'
    depends_on:
      - db

volumes:
  db_new:
